# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # å…è®¸æ‰‹åŠ¨è¿è¡Œå’Œæäº¤è§¦å‘
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # éœ€è¦å†™å…¥æƒé™æ¥æäº¤æ›´æ”¹
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub Token
          token: ${{ secrets.METRICS_ACTIOPN }}

          # è¾“å‡ºåˆ°ä»“åº“
          output_action: commit
          output_path: asset/metrics.svg   # æŒ‡å®šè¾“å‡ºæ–‡ä»¶è·¯å¾„
          commit_message: "ğŸ“Š Update GitHub metrics"

          # Metrics é…ç½®
          user: GamerMMM
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_calendar: yes
          plugin_calendar_limit: 1

